#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.34014
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SpinnerTest.Resource", IsApplication=true)]

namespace SpinnerTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int onderwerp_array = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int subonderwerpWiskunde_array = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ScoreMore = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int AccountAanmaken = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int InlogNaam = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int Inloggen = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int Logo = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int Wachtwoord = 2131099650;
			
			// aapt resource value: 0x7f060016
			public const int button1 = 2131099670;
			
			// aapt resource value: 0x7f060006
			public const int button2 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int button3 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int linearLayout1 = 2131099656;
			
			// aapt resource value: 0x7f060010
			public const int listView1 = 2131099664;
			
			// aapt resource value: 0x7f060005
			public const int myButton = 2131099653;
			
			// aapt resource value: 0x7f060013
			public const int radioButton1 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int radioButton2 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int radioButton3 = 2131099669;
			
			// aapt resource value: 0x7f060019
			public const int radioButton4 = 2131099673;
			
			// aapt resource value: 0x7f060012
			public const int radioGroup1 = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int spinner = 2131099665;
			
			// aapt resource value: 0x7f060009
			public const int textView1 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int textView2 = 2131099658;
			
<<<<<<< HEAD
			// aapt resource value: 0x7f060012
			public const int textview1 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int textview2 = 2131099667;
=======
			// aapt resource value: 0x7f06000b
			public const int textView3 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int textView4 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int textView5 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int textView6 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int textView7 = 2131099663;
			
			// aapt resource value: 0x7f060018
			public const int textview1 = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int velocity_text_view = 2131099671;
>>>>>>> origin/V2
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Inloggen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ResultaatBekijken = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ResultatenOpvragen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TentamenStarten = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int VraagBeantwoorden = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int VragenDownloaden = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int onderwerp_prompt = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int subonderwerp_prompt = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
